apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector-root
  namespace: argocd
spec:
  project: neuvector-poc
  source:
    repoURL: https://github.com/VETRI9876/argocd-neuvector.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
