apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector-root
  namespace: argocd
spec:
  project: neuvector-poc
  source:
    repoURL: https://github.com/VETRI9876/argocd-neuvector.git
    targetRevision: main
    path: argocd-neuvector/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
