apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: neuvector-poc
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/VETRI9876/argocd-neuvector.git
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true

